output_dir: "output_model"
logging_dir: "logs"
seed: 42
per_gpu_batch_size: 1
gradient_accumulation_steps: 1
num_train_epochs: 10
learning_rate: 5.0e-05
lr_scheduler: "cosine"
lr_warmup_steps: 0
adam_beta1: 0.9
adam_beta2: 0.999
adam_weight_decay: 0.01
adam_epsilon: 1e-8
pretrained_model_name_or_path: "stabilityai/stable-video-diffusion-img2vid-xt"
revision: null
pretrain_unet: null
video_folder: "dataset"
width: 512
height: 512
num_workers: 8
mixed_precision: "fp16"
conditioning_dropout_prob: 0.15
checkpointing_steps: 500
